### ISSUE TITLE
Unity 2022.2.13  windows 10.  pink screen.

### ISSUE THREAD

**Issue by 99bits** [cj-mills/Barracuda-PoseNet-Tutorial#5]
Hi Christian,

Many Thank you for your excellent articles, tutorials and project code.  It's been an incredible learning resource for me.  
I am on the latest version of Unity 2022 and testing this project in the editor and it works perfectly.  Then I built the project as a standalone for windows and got a pink screen.   Both Standard and URP build.

![InEditor](https://user-images.githubusercontent.com/22409112/229989861-50cf9f4c-1128-4c1f-b00c-968e52787320.jpg)
![pink](https://user-images.githubusercontent.com/22409112/229989879-80eec4bb-426e-4a60-811a-bac378873661.jpg)

**Comment by cj-mills** [comment]
Hi @99bits,
My first guess is the Unlit/Texture shader is not in the "Always Included Shaders" list. You can check if it is in the Project Settings → Graphics section, as in the image below.

![unity-always-included-shaders](https://user-images.githubusercontent.com/9126128/229991610-6ece22fb-47f2-46fe-b561-3b89128ba4d3.png)


You can add it manually or include the Editor script linked below, which adds it to projects automatically at build time.
* [ShaderIncludePostprocessor.cs](https://github.com/cj-mills/Unity-Media-Display/blob/main/Editor/ShaderIncludePostprocessor.cs)

**Comment by 99bits** [comment]
Big Thank you for that tip.  
I forgot that part of your tutorial.  Adding Unlit/Texture and Unlit/Color fixed on both SR and URP.  
Works fantastically.  
Cheers.

Edit, btw, on URP the video material was pink, I used another URP material that's not unity's Unlit shader so I thought that's why I didn't need to add the default unlit shader.  

Image from your tutorial which I forgot.
![add-unlit-color-shader](https://user-images.githubusercontent.com/22409112/229994638-cfb2225f-8301-4e44-8aeb-cafa8b53032e.png)
